
version: "3.9"

services:
  webui:
    container_name: "ndslabs-webui"
    image: "ndslabs/webui:dev"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=80
      # WARNING: POLLING causes high CPU usage, only use if necessary
      #- CHOKIDAR_USEPOLLING=true
      #- CHOKIDAR_INTERVAL=1500
    ports:
      - "3000:80"
      - "8081:8081"
