
version: "3.9"

services:

  keycloak:
    container_name: "wb_keycloak"
    image: "quay.io/keycloak/keycloak:17.0.1"
    user: "root"
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
      - keycloak:/opt/keycloak/data/h2/
    networks:
      - workbench
    ports:
      - "8080:8080"
    command: ["start-dev", "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"]
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  mongo:
    container_name: "wb_mongo"
    image: "mongo:5.0.3"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: username
    #  MONGO_INITDB_ROOT_PASSWORD: password
    #  MONGO_INITDB_DATABASE: ndslabs
    networks:
      - workbench
    volumes:
      - "mongo:/data/db"
    #ports:
    #  - "27017:27017"
    restart: always

  apiserver:
    container_name: "wb_apiserver"
    image: "ndslabs/apiserver:python"
    networks:
      - workbench
    depends_on:
      - keycloak
      - mongo
    build:
      context: ../workbench-apiserver-python
    env_file:
      - apiserver.env
    volumes:
      - "/Users/lambert8/.kube/config:/root/.kube/config"
    ports:
      - "5000:5000"
    restart: always


volumes:
  keycloak:
  mongo:

networks:
  workbench:
