version: "3.9"

services:
  etcd:
    container_name: "ndslabs-etcd"
    image: "quay.io/coreos/etcd:v3.3"
    ports:
      - "4001:4001"
    volumes:
      - "~/dev-data/etcd:/var/etcd/data"
    restart: always
    command: "/usr/local/bin/etcd --listen-client-urls=http://0.0.0.0:4001 --advertise-client-urls=http://127.0.0.1:4001 --data-dir=/var/etcd/data"


  apiserver:
    container_name: "ndslabs-apiserver"
    depends_on:
      - etcd
    image: "ndslabs/apiserver:cddr"

    volumes:

      # kubectl get secret -n workbench workbench-token-xxxxx -o yaml | base64decode
      - "~/go/src/github.com/workbench-apiserver-golang/token:/var/run/secrets/kubernetes.io/serviceaccount/token"
      - "~/go/src/github.com/workbench-apiserver-golang/ca.crt:/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

      # kubectl config use-context docker-desktop && cp ~/.kube/config ~/.kube/config.DOCKERMACOSX
      - "~/.kube/config.DOCKERMACOSX:/root/.kube/config"
    ports:
      - "30001:30001"
    env_file:
      - apiserver.env
    restart: always


